name: Preview Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # Étape pour vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape pour installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Utilisez la version de Node.js appropriée

      # Étape pour installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape pour exécuter le lint
      - name: Run lint
        run: npm run lint

      # Étape pour obtenir la version précédente
      - name: Get current version
        id: get_version
        run: |
          # Utiliser git describe pour obtenir la version actuelle
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Current version is $VERSION"

      # Étape pour incrémenter la version
      - name: Increment version
        id: increment_version
        run: |
          # Extraire le numéro de version majeur, mineur et patch
          IFS='.' read -r major minor patch <<< "${VERSION//v/}"
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "New version will be $new_version"

      # Étape pour se connecter à EAS
      - name: EAS Login
        run: eas login

      # Étape pour mettre à jour avec le message de version dynamique
      - name: EAS Update
        run: eas update --branch preview --message "Preview $NEW_VERSION"